// The generated pages must match the config they claim to be generated from.
//
// Owner, 2026-10-05: "make mine map and tool actuaually work so i can see what
// your talking about with this change". They ran -- and showed the wrong game.
//
// TOOL_TIER_SPAN moved 16 -> 10 -> 7 that day. mine-map.html was regenerated
// after the first move and not the second, so it sat on span 10: a tier-30 pick
// read 6,109 damage where the game said 892. Nothing looked broken. Every
// number was wrong.
//
// upgrade-calculator.html had the same disease for longer -- 121 ores and a
// 1000-level cap against an 82-ore, 100-level game -- and tools/verify/check.js
// read ITS copy of the formula, so the harness agreed with the stale page
// instead of with the game.
//
// Both generators take --check now. This runs them. A page that cannot be
// regenerated byte-for-byte is a page that has drifted.
//
// Run: node tools/verify/generated-fresh.js
const { execFileSync } = require("child_process");
const path = require("path");
const ROOT = path.join(__dirname, "..", "..");

const GENS = [
  ["mine map", "tools/gen-mine-map.js"],
  ["upgrade bench", "tools/gen/upgrade-calculator.js"],
];

let fails = 0;
for (const [label, gen] of GENS) {
  try {
    const out = execFileSync(process.execPath, [gen, "--check"],
      { cwd: ROOT, encoding: "utf8" });
    console.log("  ok    " + label + "   " + out.trim().replace(/^ok\s*/, ""));
  } catch (e) {
    fails++;
    const msg = ((e.stdout || "") + (e.stderr || "")).trim();
    console.log("  FAIL  " + label + " is stale");
    for (const l of msg.split("\n")) console.log("        " + l);
  }
}

// depth-sheet.json feeds the mine map, so a stale one poisons it silently.
// It is cheap to rebuild and compare.
try {
  execFileSync(process.execPath, ["tools/depth-sheet-data.js"],
    { cwd: ROOT, encoding: "utf8", stdio: "pipe" });
  const out = execFileSync(process.execPath, ["tools/gen-mine-map.js", "--check"],
    { cwd: ROOT, encoding: "utf8" });
  console.log("  ok    mine map still matches after rebuilding depth-sheet.json");
} catch (e) {
  fails++;
  console.log("  FAIL  rebuilding depth-sheet.json changes the mine map" +
    " -- build/depth-sheet.json was stale");
  console.log("        regenerate: node tools/depth-sheet-data.js" +
    " then node tools/gen-mine-map.js");
}

console.log(fails === 0
  ? ">>> generated pages are current"
  : ">>> " + fails + " stale");
process.exit(fails === 0 ? 0 : 1);
