// Regenerate MineSkillData's node percentages from the energies and the live
// MineStats weights.
//
// MineSkillData says "GENERATED by skills/gen.js + skills/emit.js. Edit those,
// not this file" -- and neither was ever in the repo. So the node percentages
// were frozen against weights that have since moved, and by 2026-10-04 the best
// road was 2.44x the worst against a header promising 1.00x.
//
// This is that generator, rebuilt from the rule the file states: "every node is
// worth a BUDGET IN MINESTATS POINTS, and its percentages are derived by
// dividing that budget by each stat's weight."
//
// TOPOLOGY IS NOT TOUCHED. Ids, names, angles, rows, costs, prereqs, xor groups,
// rivals and cross-links are read and written back unchanged. The ONLY thing
// rewritten is each node's `stats = { ... }`. This is a re-pricing, not a
// redesign, so a saved tree still points at nodes that exist.
//
//   node tools/skills/gen.js            # rewrite in place
//   node tools/skills/gen.js --check    # report only, exit 1 if it would change
const fs = require("fs");
const path = require("path");
const ROOT = path.resolve(__dirname, "../..");
const TREE = path.join(ROOT, "src/ReplicatedStorage/Mine/Shared/MineSkillData.luau");
const STATS = path.join(ROOT, "src/ReplicatedStorage/Mine/Shared/MineStats.luau");
const checkOnly = process.argv.includes("--check");

// How a node's budget is split. Documented here because it is a DESIGN choice,
// not something recoverable from the old data -- the original generator's exact
// shares cannot be solved for now that the weights behind them have moved.
//
// The invariant that matters is not the split, it is that every node spends its
// whole `points` budget and no more. That is what makes two equally-priced
// nodes equally good whatever stats they touch, and it is asserted downstream.
const SHARES = {
  three: [0.5, 0.3, 0.2],       // root, key   -> primary, secondary, tertiary
  two: [0.65, 0.35],            // split, cross -> the pair that row uses
  fuse: [0.5, 0.5],             // two energies' primaries, evenly
  cap: [0.35, 0.15, 0.35, 0.15], // both energies' primary + secondary
};

const weights = {};
{
  const src = fs.readFileSync(STATS, "utf8");
  const block = (src.match(/MineStats\.STATS = \{([\s\S]*?)\n\}/) || ["", ""])[1];
  for (const m of block.matchAll(/^\t(\w+)\s*=\s*\{[^}]*?weight\s*=\s*([\d.]+)/gm)) {
    weights[m[1]] = Number(m[2]);
  }
}
if (Object.keys(weights).length < 15) {
  console.error("FAIL could not read MineStats weights");
  process.exit(1);
}

let tree = fs.readFileSync(TREE, "utf8");
const energies = {};
{
  const block = (tree.match(/MineSkillData\.ENERGIES = \{([\s\S]*?)\n\}/) || ["", ""])[1];
  for (const m of block.matchAll(
    /\{ id = "(\w+)", name = "(\w+)",[\s\S]*?primary = "(\w+)", secondary = "(\w+)", tertiary = "(\w+)" \}/g)) {
    energies[m[1]] = { id: m[1], name: m[2], roles: [m[3], m[4], m[5]] };
  }
}
if (Object.keys(energies).length !== 10) {
  console.error(`FAIL expected 10 energies, read ${Object.keys(energies).length}`);
  process.exit(1);
}
const byName = {};
for (const e of Object.values(energies)) byName[e.name] = e;

// Which (stat, share) pairs a node spends on, from its id, row and energy field.
function planFor(id, row, energyField) {
  const names = energyField.split("+").map((s) => s.trim());
  const a = byName[names[0]];
  const b = names[1] ? byName[names[1]] : null;
  if (!a) return null;
  if (row === "fuse") {
    if (!b) return null;
    return [[a.roles[0], SHARES.fuse[0]], [b.roles[0], SHARES.fuse[1]]];
  }
  if (row === "cap") {
    if (!b) return null;
    return [
      [a.roles[0], SHARES.cap[0]], [a.roles[1], SHARES.cap[1]],
      [b.roles[0], SHARES.cap[2]], [b.roles[1], SHARES.cap[3]],
    ];
  }
  if (row === "root" || row === "key") {
    return a.roles.map((stat, i) => [stat, SHARES.three[i]]);
  }
  // split and cross each come in an A and a B flavour: A takes the primary and
  // secondary, B takes the secondary and tertiary. That is what makes the two
  // roads out of a root actually different.
  const isB = /(?:split|cross)B$/.test(id);
  const pair = isB ? [a.roles[1], a.roles[2]] : [a.roles[0], a.roles[1]];
  return pair.map((stat, i) => [stat, SHARES.two[i]]);
}

let rewritten = 0, changed = 0, skipped = [];
tree = tree.replace(
  /(\{ id = "([\w.]+)", name = "[^"]*", energy = "([^"]*)",[\s\S]*?row = "(\w+)",[\s\S]*?points = (\d+),[\s\S]*?)stats = \{([^}]*)\}/g,
  (whole, head, id, energyField, row, points, oldStats) => {
    const plan = planFor(id, row, energyField);
    if (!plan) { skipped.push(id); return whole; }
    const budget = Number(points) / 100;
    // Merge duplicate stats: a cap whose two energies share a stat spends both
    // shares on it rather than printing the key twice.
    const merged = new Map();
    for (const [stat, share] of plan) {
      merged.set(stat, (merged.get(stat) || 0) + share);
    }
    const parts = [];
    for (const [stat, share] of merged) {
      const w = weights[stat];
      if (!w) { skipped.push(`${id}:${stat}`); return whole; }
      // points -> percent: budget * share, divided by what a point of this
      // stat costs. Rounded to 4dp, which is what the original table used.
      parts.push(`${stat} = ${Number(((budget * share) / w).toFixed(4))}`);
    }
    const next = `stats = { ${parts.join(", ")} }`;
    rewritten++;
    if (next !== `stats = {${oldStats}}`) changed++;
    return head + next;
  });

if (skipped.length) {
  console.error("FAIL could not plan these nodes: " + skipped.join(", "));
  process.exit(1);
}
console.log(`  planned ${rewritten} nodes, ${changed} would change`);
if (checkOnly) {
  if (changed) console.error(">>> gen: MineSkillData is STALE — run node tools/skills/gen.js");
  else console.log(">>> gen: MineSkillData is up to date");
  process.exit(changed ? 1 : 0);
}
fs.writeFileSync(TREE, tree);
console.log(">>> gen: MineSkillData regenerated");
